name: Build and Release Sultan Kernels

permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions
  
on:
  workflow_dispatch:
        
jobs:
  build-kernel-zuma:
    uses: ./.github/workflows/sultan.yml
    secrets: inherit
    with:
      codename: "zuma"
      repo: "android_kernel_google_zuma"
      android_version: "android14"
      kernel_version: "6.1"

  trigger-release:
    runs-on: ubuntu-latest
    needs:
        - build-kernel-zuma
    env:
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: Sultan_KernelSU_SUSFS
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_NAME: "Sultan Kernels With KernelSU Next & SUSFS v1.5.12"
      RELEASE_NOTES: |
        This release contains KernelSU Next and SUSFS v1.5.12
        
        ⚠️ **COMPATIBILITY NOTICE** ⚠️
        Please ensure compatibility by comparing release dates with official Sultan kernel releases
        
        Module: 
        -> https://github.com/sidex15/ksu_module_susfs
        
        Managers:
        -> https://nightly.link/KernelSU-Next/KernelSU-Next/workflows/build-manager-spoofed/next/Manager.zip!
        
        Features:
        [+] KernelSU Next
        [+] SUSFS v1.5.12
        [+] Magic Mount Support

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Get the Latest Tag from GitHub
      - name: Generate and Create New Tag
        run: |
            # Generate a new tag based on the current commit SHA
            NEW_TAG="v1.5.12-$(git rev-parse --short HEAD)"
            
            # Output the new tag to be used
            echo "New tag: $NEW_TAG"
            
            # Set the new tag as an environment variable to be used in later steps
            echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
            
            # Create the tag in the repository
            git tag $NEW_TAG
            git push origin $NEW_TAG
            
      # Download Artifacts for A12 (Only if A12 Build is successful or input is true or empty)
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts

      # Create GitHub Release and upload files if make_release is true
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}  # Use the generated tag for the release
          release_name: ${{ env.RELEASE_NAME }}  # Pass the RELEASE_NAME to the action
          body: ${{ env.RELEASE_NOTES }}  # Pass the RELEASE_NOTES to the action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets Dynamically
        run: |
          # Loop through all files in the downloaded-artifacts directory
          for file in ./downloaded-artifacts/*/*; do
              # Skip directories
              if [ -d "$file" ]; then
                  continue
              fi

              # Upload the file to the GitHub release
              echo "Uploading $file..."
              gh release upload ${{ env.NEW_TAG }} "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_TAG: ${{ env.NEW_TAG }}

      # Display Files Uploaded
      - name: Display Files Uploaded
        run: |
          echo "GitHub release created with the following files:"
          ls ./downloaded-artifacts/**/*
